Rails.application.config.to_prepare do
  Team.data = [
      {id: 1, name: 'ベガルタ仙台', api_name: '仙台'},
      {id: 2, name: 'モンテディオ山形', api_name: '山形'},
      {id: 3, name: '浦和レッズ', api_name: '浦和'},
      {id: 4, name: '川崎フロンターレ', api_name: '川崎Ｆ'},
      {id: 5, name: '清水エスパルス', api_name: '清水'},
      {id: 6, name: 'サンフレッチェ広島', api_name: '広島'},
      {id: 7, name: 'サガン鳥栖', api_name: '鳥栖'},
      {id: 8, name: '柏レイソル', api_name: '柏'},
      {id: 9, name: '松本山雅ＦＣ', api_name: '松本'},
      {id: 10, name: '名古屋グランパス', api_name: '名古屋'},
      {id: 11, name: 'ＦＣ東京', api_name: 'FC東京'},
      {id: 12, name: 'ガンバ大阪', api_name: 'Ｇ大阪'},
      {id: 13, name: 'アルビレックス新潟', api_name: '新潟'},
      {id: 14, name: 'ヴィッセル神戸', api_name: '神戸'},
      {id: 15, name: '鹿島アントラーズ', api_name: '鹿島'},
      {id: 16, name: '横浜F・マリノス', api_name: '横浜FM'},
      {id: 17, name: '湘南ベルマーレ', api_name: '湘南'},
      {id: 18, name: 'ヴァンフォーレ甲府', api_name: '甲府'},
#      {id: 19, name: '', api_name: ''},
#      {id: 20, name: '', api_name: ''},
#      {id: 21, name: '', api_name: ''},
#      {id: 22, name: '', api_name: ''},
#      {id: 23, name: '', api_name: ''},
#      {id: 24, name: '', api_name: ''},
#      {id: 25, name: '', api_name: ''},
#      {id: 26, name: '', api_name: ''},
#      {id: 27, name: '', api_name: ''},
#      {id: 28, name: '', api_name: ''},
#      {id: 29, name: '', api_name: ''},
#      {id: 30, name: '', api_name: ''},
#      {id: 31, name: '', api_name: ''},
#      {id: 31, name: '', api_name: ''},
#      {id: 32, name: '', api_name: ''},
#      {id: 33, name: '', api_name: ''},
  ]
end